apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center:7.4.0
        ports:
        - containerPort: 9021
        env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"  # Kết nối tới Kafka trong cluster
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: "http://schema-registry-service:8081"
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "1"
        - name: CONFLUENT_METRICS_ENABLE
          value: "false"